--------------------------------------------------------
--  파일이 생성됨 - 일요일-6월-12-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACADEMY
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."ACADEMY" 
   (	"ACA_CODE" VARCHAR2(20 BYTE), 
	"ACA_NAME" NVARCHAR2(50), 
	"ACA_SUBJECT" NVARCHAR2(10), 
	"ACA_ADDR" NVARCHAR2(255), 
	"ACA_INFO" NVARCHAR2(1024), 
	"ACA_IMG" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOL_TABLESPACE" 
 LOB ("ACA_IMG") STORE AS BASICFILE (
  TABLESPACE "SCHOOL_TABLESPACE" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index ACADEMY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."ACADEMY_PK" ON "SCHOOL"."ACADEMY" ("ACA_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOL_TABLESPACE" ;
--------------------------------------------------------
--  Constraints for Table ACADEMY
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."ACADEMY" ADD CONSTRAINT "ACADEMY_PK" PRIMARY KEY ("ACA_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOL_TABLESPACE"  ENABLE;
  ALTER TABLE "SCHOOL"."ACADEMY" MODIFY ("ACA_ADDR" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."ACADEMY" MODIFY ("ACA_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."ACADEMY" MODIFY ("ACA_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."ACADEMY" MODIFY ("ACA_CODE" NOT NULL ENABLE);
