--------------------------------------------------------
--  파일이 생성됨 - 일요일-6월-12-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLASS
--------------------------------------------------------

  CREATE TABLE "SCHOOL"."CLASS" 
   (	"CLASS_CODE" VARCHAR2(20 BYTE), 
	"ACA_CODE" VARCHAR2(20 BYTE), 
	"CLASS_NAME" NVARCHAR2(20), 
	"CLASS_SUBJECT" NVARCHAR2(20), 
	"CLASS_FEE" NUMBER, 
	"SCHE_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOL_TABLESPACE" ;
--------------------------------------------------------
--  DDL for Index CLASS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCHOOL"."CLASS_PK" ON "SCHOOL"."CLASS" ("CLASS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOL_TABLESPACE" ;
--------------------------------------------------------
--  Constraints for Table CLASS
--------------------------------------------------------

  ALTER TABLE "SCHOOL"."CLASS" ADD CONSTRAINT "CLASS_PK" PRIMARY KEY ("CLASS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOL_TABLESPACE"  ENABLE;
  ALTER TABLE "SCHOOL"."CLASS" MODIFY ("SCHE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."CLASS" MODIFY ("CLASS_FEE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."CLASS" MODIFY ("CLASS_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."CLASS" MODIFY ("CLASS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."CLASS" MODIFY ("ACA_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL"."CLASS" MODIFY ("CLASS_CODE" NOT NULL ENABLE);
