--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-31-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table 결제정보
--------------------------------------------------------

  CREATE TABLE "TEAMPJ"."결제정보" 
   (	"MEM_PAY_ID" VARCHAR2(20 BYTE), 
	"LEC_PAY_CODE" NUMBER, 
	"PAY_PAY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Table 수업
--------------------------------------------------------

  CREATE TABLE "TEAMPJ"."수업" 
   (	"LEC_CODE" NUMBER, 
	"BELONG_LEC_CODE" NUMBER, 
	"LEC_NAME" NVARCHAR2(50), 
	"LEC_SUBJECT" NVARCHAR2(50), 
	"LEC_PAY" NUMBER, 
	"SCHE_LEC_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Table 수업_BELONG
--------------------------------------------------------

  CREATE TABLE "TEAMPJ"."수업_BELONG" 
   (	"BELONG_CODE" NUMBER, 
	"LEC_BELONG_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Table 스케줄
--------------------------------------------------------

  CREATE TABLE "TEAMPJ"."스케줄" 
   (	"SCHE_CODE" NUMBER, 
	"SCHE_DAY" DATE, 
	"SCHE_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Table 학원
--------------------------------------------------------

  CREATE TABLE "TEAMPJ"."학원" 
   (	"BELONG_ACA_CODE" NUMBER, 
	"ACA_NAME" NVARCHAR2(100), 
	"ACA_SUBJECT" NVARCHAR2(25), 
	"ACA_ADDRS" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Table 회원정보
--------------------------------------------------------

  CREATE TABLE "TEAMPJ"."회원정보" 
   (	"MEM_ID" VARCHAR2(20 BYTE), 
	"MEM_PASSWORD" VARCHAR2(20 BYTE), 
	"MEM_NAME" NVARCHAR2(5), 
	"MEM_TEL" VARCHAR2(20 BYTE), 
	"MEM_ADDRS" NVARCHAR2(100), 
	"MEM_EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
REM INSERTING into TEAMPJ."결제정보"
SET DEFINE OFF;
REM INSERTING into TEAMPJ."수업"
SET DEFINE OFF;
REM INSERTING into TEAMPJ."수업_BELONG"
SET DEFINE OFF;
REM INSERTING into TEAMPJ."스케줄"
SET DEFINE OFF;
REM INSERTING into TEAMPJ."학원"
SET DEFINE OFF;
REM INSERTING into TEAMPJ."회원정보"
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index 수업_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMPJ"."수업_PK" ON "TEAMPJ"."수업" ("LEC_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Index 수업_BELONG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMPJ"."수업_BELONG_PK" ON "TEAMPJ"."수업_BELONG" ("BELONG_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Index 스케줄_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMPJ"."스케줄_PK" ON "TEAMPJ"."스케줄" ("SCHE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  DDL for Index 회원정보_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMPJ"."회원정보_PK" ON "TEAMPJ"."회원정보" ("MEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER" ;
--------------------------------------------------------
--  Constraints for Table 결제정보
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."결제정보" MODIFY ("MEM_PAY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table 수업
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."수업" ADD CONSTRAINT "수업_PK" PRIMARY KEY ("LEC_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER"  ENABLE;
  ALTER TABLE "TEAMPJ"."수업" MODIFY ("BELONG_LEC_CODE" NOT NULL ENABLE);
  ALTER TABLE "TEAMPJ"."수업" MODIFY ("LEC_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table 수업_BELONG
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."수업_BELONG" ADD CONSTRAINT "BELONG_PK" PRIMARY KEY ("BELONG_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER"  ENABLE;
  ALTER TABLE "TEAMPJ"."수업_BELONG" MODIFY ("BELONG_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table 스케줄
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."스케줄" ADD CONSTRAINT "스케줄_PK" PRIMARY KEY ("SCHE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER"  ENABLE;
  ALTER TABLE "TEAMPJ"."스케줄" MODIFY ("SCHE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table 학원
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."학원" MODIFY ("BELONG_ACA_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table 회원정보
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."회원정보" ADD CONSTRAINT "회원정보_PK" PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHOOLVER"  ENABLE;
  ALTER TABLE "TEAMPJ"."회원정보" MODIFY ("MEM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table 결제정보
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."결제정보" ADD CONSTRAINT "결제정보_FK1" FOREIGN KEY ("LEC_PAY_CODE")
	  REFERENCES "TEAMPJ"."수업" ("LEC_CODE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TEAMPJ"."결제정보" ADD CONSTRAINT "결제정보_FK2" FOREIGN KEY ("MEM_PAY_ID")
	  REFERENCES "TEAMPJ"."회원정보" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table 수업
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."수업" ADD CONSTRAINT "수업_FK1" FOREIGN KEY ("BELONG_LEC_CODE")
	  REFERENCES "TEAMPJ"."수업_BELONG" ("BELONG_CODE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TEAMPJ"."수업" ADD CONSTRAINT "수업_FK2" FOREIGN KEY ("SCHE_LEC_CODE")
	  REFERENCES "TEAMPJ"."스케줄" ("SCHE_CODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table 수업_BELONG
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."수업_BELONG" ADD CONSTRAINT "수업_BELONG_FK1" FOREIGN KEY ("LEC_BELONG_CODE")
	  REFERENCES "TEAMPJ"."수업" ("LEC_CODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table 학원
--------------------------------------------------------

  ALTER TABLE "TEAMPJ"."학원" ADD CONSTRAINT "학원_FK1" FOREIGN KEY ("BELONG_ACA_CODE")
	  REFERENCES "TEAMPJ"."수업_BELONG" ("BELONG_CODE") ON DELETE CASCADE ENABLE;
